import { test, expect } from '@playwright/test';
import fs from 'node:fs';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
import { createHash } from 'node:crypto';
const url=pathToFileURL(path.resolve('dist/branchsheet.html')).href,out=path.resolve('evidence/browser-downloads');
const telemetry=new Map();
test.beforeEach(async({page,context,browser},info)=>{
 const record={pageErrors:[],consoleErrors:[],externalRequests:[],chromiumArguments:[]};telemetry.set(info.testId,record);
 page.on('pageerror',error=>record.pageErrors.push(error.message));page.on('console',message=>{if(message.type()==='error')record.consoleErrors.push(message.text());});context.on('request',request=>{if(/^https?:/.test(request.url()))record.externalRequests.push(request.url());});
 const session=await browser.newBrowserCDPSession();record.chromiumArguments=(await session.send('Browser.getBrowserCommandLine')).arguments;await session.detach();
 expect(record.chromiumArguments).not.toContain('--no-sandbox');expect(record.chromiumArguments).not.toContain('--disable-setuid-sandbox');
});
test.afterEach(async({},info)=>{const record=telemetry.get(info.testId);fs.writeFileSync(info.outputPath('browser-checks.json'),JSON.stringify(record,null,2)+'\n');expect(record.pageErrors).toEqual([]);expect(record.consoleErrors).toEqual([]);expect(record.externalRequests).toEqual([]);telemetry.delete(info.testId);});
async function mobileEdges(page,info,language){await page.setViewportSize({width:390,height:844});const scroller=page.locator('.table-scroll');await scroller.evaluate(e=>e.scrollLeft=0);await page.screenshot({path:info.outputPath('mobile-'+language+'-left.png'),fullPage:true});await scroller.evaluate(e=>e.scrollLeft=e.scrollWidth);expect(await page.locator('th:last-child').evaluate(e=>{const cell=e.getBoundingClientRect(),box=e.closest('.table-scroll').getBoundingClientRect();return cell.left>=box.left&&cell.right<=box.right+1;})).toBeTruthy();const details=page.locator('#rows button').first();expect(await details.evaluate(e=>getComputedStyle(e).whiteSpace)).toBe('nowrap');expect(await details.evaluate(e=>e.getBoundingClientRect().right<=e.closest('.table-scroll').getBoundingClientRect().right+1)).toBeTruthy();await page.screenshot({path:info.outputPath('mobile-'+language+'-right.png'),fullPage:true});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();}
async function fixturePdf(page,info,language){await page.emulateMedia({media:'print'});await page.pdf({path:info.outputPath('review-'+language+'.pdf'),format:'A4',landscape:true,printBackground:true});await page.emulateMedia({media:'screen'});}

const bytes=name=>fs.readFileSync(path.resolve('evidence',name)),digest=b=>createHash('sha256').update(b).digest('hex');
async function open(page,context){await context.setOffline(true);await page.goto(url);await expect(page.locator('#build')).toBeDisabled();}
async function pair(page,map,prior=null){await page.locator('#map-file').setInputFiles(path.resolve('evidence',map));if(prior)await page.locator('#prior-file').setInputFiles(path.resolve('evidence',prior));else await page.locator('#clear-prior').click();}
async function build(page){await page.locator('#build').click();await expect(page.locator('#download')).toBeEnabled({timeout:120000});}
async function download(page,name,button='download'){fs.mkdirSync(out,{recursive:true});const event=page.waitForEvent('download');await page.locator('#'+button).click();const item=await event;await item.saveAs(path.join(out,name));return fs.readFileSync(path.join(out,name));}
async function bufferMap(page,text,name='test.mm'){await page.locator('#map-file').setInputFiles({name,mimeType:'application/xml',buffer:Buffer.from(text)});}

test('actual native maps and Calc-saved workbook produce real offline downloads, repeat and restore',async({page,context},info)=>{
 const errors=[],external=[];page.on('pageerror',e=>errors.push(e.message));context.on('request',r=>{if(/^https?:/.test(r.url()))external.push(r.url());});await open(page,context);
 await pair(page,'before.mm');await build(page);expect((await download(page,'initial.xlsx')).equals(bytes('initial.xlsx'))).toBeTruthy();
 await pair(page,'updated.mm','calc-annotated.xlsx');await build(page);await expect(page.locator('#map-name')).toContainText('照合済み');await expect(page.locator('#map-file')).toBeHidden();await expect(page.locator('#choose-map')).toBeVisible();expect(await page.locator('h1').textContent()).toBe('ツリーが変わっても、\n書き込んだ言葉を残す。');const refreshed=await download(page,'refreshed.xlsx');expect(refreshed.equals(bytes('refreshed.xlsx'))).toBeTruthy();expect((await download(page,'repeated.xlsx')).equals(refreshed)).toBeTruthy();
 const receipt=JSON.parse((await download(page,'review.json','receipt')).toString());expect(receipt.mapSHA256).toBe(digest(bytes('updated.mm')));expect(receipt.priorSHA256).toBe(digest(bytes('calc-annotated.xlsx')));expect(receipt.workbookSHA256).toBe(digest(refreshed));expect(receipt.counts).toEqual({all:6,active:5,removed:1,added:1,renamed:1,moved:1,restored:0,structure:0,unchanged:3});
 await page.locator('#filter').selectOption('moved');await expect(page.locator('#rows tr')).toHaveCount(1);await expect(page.locator('#rows')).toContainText('Beta');await expect(page.locator('#rows')).toContainText('007');await expect(page.locator('#rows')).toContainText('=1+1');expect((await download(page,'filtered-scope.xlsx')).equals(refreshed)).toBeTruthy();
 await page.locator('#rows button').click();await expect(page.getByRole('dialog')).toBeVisible();await expect(page.locator('#detail-content')).toContainText('line1\nline2');await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).not.toBeVisible();await page.locator('#filter').selectOption('all');await expect(page.locator('#rows tr')).toHaveCount(6);
 await page.screenshot({path:info.outputPath('desktop-ja.png'),fullPage:true});await fixturePdf(page,info,'ja');await mobileEdges(page,info,'ja');await page.locator('#language').click();await mobileEdges(page,info,'en');await page.setViewportSize({width:1365,height:950});await page.screenshot({path:info.outputPath('desktop-en.png'),fullPage:true});await fixturePdf(page,info,'en');await page.locator('#language').click();await page.setViewportSize({width:1280,height:950});await page.addStyleTag({content:':root{font-size:200%}'});await page.screenshot({path:info.outputPath('enlarged-text-ja.png'),fullPage:true});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();
 await page.locator('#prior-file').setInputFiles(path.join(out,'refreshed.xlsx'));await build(page);expect((await download(page,'unchanged.xlsx')).equals(refreshed)).toBeTruthy();await page.locator('#map-file').setInputFiles(path.resolve('evidence/restored.mm'));await build(page);expect((await download(page,'restored.xlsx')).equals(bytes('restored.xlsx'))).toBeTruthy();expect(errors).toEqual([]);expect(external).toEqual([]);
});

test('schema rejection, literal markup, keyboard focus and repeat same file remain inert',async({page,context},info)=>{
 await open(page,context);await page.locator('#language').click();await page.locator('#choose-map').focus();await page.keyboard.press('Tab');await page.keyboard.press('Shift+Tab');expect(await page.locator('#choose-map').evaluate(e=>getComputedStyle(e).outlineStyle)).not.toBe('none');const chooserEvent=page.waitForEvent('filechooser');await page.locator('#choose-map').press('Enter');await (await chooserEvent).setFiles(path.resolve('evidence/before.mm'));await expect(page.locator('#map-name')).toContainText('before.mm');
 await page.locator('#demo').click();await build(page);await pair(page,'updated.mm','negative-changed-parent.xlsx');await page.locator('#build').click();await expect(page.locator('#status')).toHaveClass('error');await expect(page.locator('#download')).toBeDisabled();
 for(const xml of ['<map><node ID="R" TEXT="X"><node ID="R" TEXT="Y"/></node></map>','<!DOCTYPE map [<!ENTITY evil "PRIVATE_SENTINEL">]><map><node ID="R" TEXT="&evil;"/></map>','<map><node ID="R" TEXT="=1+1"/></map>']){await bufferMap(page,xml);await page.locator('#clear-prior').click();await page.locator('#build').click();await expect(page.locator('#status')).toHaveClass('error');await expect(page.locator('#download')).toBeDisabled();expect(await page.locator('body').textContent()).not.toContain('PRIVATE_SENTINEL');}
 await bufferMap(page,'<map><node ID="R" TEXT="&lt;img src=x onerror=PRIVATE_CODE&gt;日本語"/></map>');await build(page);expect(await page.locator('img').count()).toBe(0);await expect(page.locator('#rows')).toContainText('<img src=x onerror=PRIVATE_CODE>日本語');
 const good=Buffer.from('<map><node ID="R" TEXT="Valid"/></map>'),bad=Buffer.from(good);bad[bad.indexOf('Valid')]=255;await page.locator('#map-file').setInputFiles({name:'same.mm',mimeType:'application/xml',buffer:bad});await page.locator('#build').click();await expect(page.locator('#status')).toHaveClass('error');await expect(page.locator('#map-file')).toHaveValue('');await page.locator('#map-file').setInputFiles({name:'same.mm',mimeType:'application/xml',buffer:good});await build(page);await expect(page.locator('#rows')).toContainText('Valid');
 await page.locator('#map-file').setInputFiles({name:'large.mm',mimeType:'application/xml',buffer:Buffer.alloc(16*1024*1024+1,32)});await expect(page.locator('#status')).toHaveClass('error');await expect(page.locator('#build')).toBeDisabled();await expect(page.locator('#download')).toBeDisabled();
 await page.locator('#demo').click();await page.evaluate(()=>{window.Worker=class{constructor(){throw Error('blocked');}};});await page.locator('#build').click();await expect(page.locator('#status')).toContainText('Worker');await expect(page.locator('#download')).toBeDisabled();
});

test('pending reads, cancellation and superseding pairs cannot export stale data',async({page,context})=>{
 await open(page,context);await page.locator('#language').click();await page.evaluate(()=>{const original=File.prototype.arrayBuffer;window.__reads={pending:[],completed:0};File.prototype.arrayBuffer=function(){const result=original.call(this);if(this.name!=='slow.mm')return result;return new Promise(resolve=>result.then(bytes=>window.__reads.pending.push({resolve,bytes}))).then(bytes=>{window.__reads.completed++;return bytes;});};});
 const releaseRead=async count=>{await page.evaluate(()=>{const item=window.__reads.pending.shift();item.resolve(item.bytes);});await expect.poll(()=>page.evaluate(()=>window.__reads.completed)).toBe(count);};
 await bufferMap(page,'<map><node ID="SLOW" TEXT="STALE_SOURCE"/></map>','slow.mm');await page.locator('#build').click();await expect.poll(()=>page.evaluate(()=>window.__reads.pending.length)).toBe(1);await page.locator('#reset').click();await releaseRead(1);await expect(page.locator('#download')).toBeDisabled();await expect(page.locator('#build')).toBeDisabled();
 await bufferMap(page,'<map><node ID="SLOW" TEXT="STALE_SOURCE"/></map>','slow.mm');await page.locator('#build').click();await expect.poll(()=>page.evaluate(()=>window.__reads.pending.length)).toBe(1);await bufferMap(page,'<map><node ID="FAST" TEXT="Fresh"/></map>','fast.mm');await build(page);await releaseRead(2);await expect(page.locator('#rows')).toContainText('Fresh');expect(await page.locator('#rows').textContent()).not.toContain('STALE_SOURCE');
 await bufferMap(page,'<map><node ID="SLOW" TEXT="CANCELLED"/></map>','slow.mm');await page.locator('#build').click();await expect.poll(()=>page.evaluate(()=>window.__reads.pending.length)).toBe(1);await page.locator('#cancel').click();await releaseRead(3);await expect(page.locator('#download')).toBeDisabled();await expect(page.locator('#status')).toContainText('cancelled');
 await bufferMap(page,'<map><node ID="BASE" TEXT="Reviewed baseline"/></map>');await build(page);await expect(page.locator('#map-name')).toContainText('Reviewed');
 await page.evaluate(()=>{const Original=Worker;window.__workerGate={hold:true,pending:[],released:0};window.Worker=class extends Original{constructor(...args){super(...args);this.addEventListener('message',event=>{if(event.data.type==='built'&&window.__workerGate.hold){event.stopImmediatePropagation();window.__workerGate.pending.push({target:this,data:event.data});}});}};window.__releaseWorker=()=>{window.__workerGate.hold=false;for(const item of window.__workerGate.pending.splice(0)){item.target.dispatchEvent(new MessageEvent('message',{data:item.data}));window.__workerGate.released++;}};});
 await page.locator('#build').click();await expect.poll(()=>page.evaluate(()=>window.__workerGate.pending.length)).toBe(1);await expect(page.locator('#map-name')).toContainText('not yet reviewed');await page.locator('#cancel').click();await expect(page.locator('#map-name')).toContainText('not yet reviewed');await page.evaluate(()=>window.__releaseWorker());await expect.poll(()=>page.evaluate(()=>window.__workerGate.released)).toBe(1);await expect(page.locator('#download')).toBeDisabled();await expect(page.locator('#status')).toContainText('cancelled');
 await page.evaluate(()=>window.__workerGate.hold=true);await bufferMap(page,'<map><node ID="OLD" TEXT="REAL_WORKER_OLD"/></map>');await page.locator('#build').click();await expect.poll(()=>page.evaluate(()=>window.__workerGate.pending.length)).toBe(1);await bufferMap(page,'<map><node ID="LATEST" TEXT="Newest pair"/></map>');await page.evaluate(()=>window.__workerGate.hold=false);await build(page);await page.evaluate(()=>window.__releaseWorker());await expect.poll(()=>page.evaluate(()=>window.__workerGate.released)).toBe(2);await expect(page.locator('#rows')).toContainText('Newest pair');expect(await page.locator('#rows').textContent()).not.toContain('REAL_WORKER_OLD');
 await page.locator('#demo').click();await build(page);await page.evaluate(()=>{const original=File.prototype.arrayBuffer;File.prototype.arrayBuffer=function(){return this.name==='unreadable.mm'?Promise.reject(Error('PRIVATE_READ_ERROR')):original.call(this);};});await bufferMap(page,'<map><node ID="R" TEXT="X"/></map>','unreadable.mm');await page.locator('#build').click();await expect(page.locator('#status')).toContainText('could not be read');expect(await page.locator('body').textContent()).not.toContain('PRIVATE_READ_ERROR');await expect(page.locator('#download')).toBeDisabled();
});

test('20,000-row actual browser build, bounded DOM pagination and explicit print page',async({page,context},info)=>{
 await open(page,context);await page.locator('#language').click();await pair(page,'scale-updated.mm','scale-prior.xlsx');await build(page);const actual=await download(page,'scale-refreshed.xlsx');expect(actual.equals(bytes('scale-refreshed.xlsx'))).toBeTruthy();await expect(page.locator('#rows tr')).toHaveCount(50);expect(await page.locator('tr').count()).toBe(51);await expect(page.locator('#page-label')).toContainText('20,100');await page.locator('#next').click();await expect(page.locator('#page-label')).toContainText('Page 2');await expect(page.locator('#rows tr')).toHaveCount(50);await page.locator('#filter').selectOption('removed');await expect(page.locator('#page-label')).toContainText('100 rows');await page.locator('#next').click();await expect(page.locator('#page-label')).toContainText('Page 2 of 2');await expect(page.locator('#rows tr')).toHaveCount(50);
 await page.locator('#search').fill('N99');await expect(page.locator('#rows tr')).toHaveCount(1);await expect(page.locator('#rows')).toContainText('N99');await page.emulateMedia({media:'print'});await expect(page.locator('#inputs')).toBeHidden();await expect(page.locator('.print-note')).toBeVisible();await page.screenshot({path:info.outputPath('bounded-print-preview.png'),fullPage:true});await page.pdf({path:info.outputPath('one-row-preview.pdf'),format:'A4',landscape:true,printBackground:true});await page.emulateMedia({media:'screen'});await page.setViewportSize({width:390,height:844});await page.screenshot({path:info.outputPath('scale-mobile-en.png'),fullPage:true});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();
});
